(function(){"use strict";if(window.__mkExamMode||window.MkStudySession)return;const KEY="mk_account_study_session_v1",ID=/^study-session-[A-Za-z0-9_-]{8,100}$/;const script=document.currentScript||document.querySelector('script[src*="study-session.js"]');const siteRoot=new URL("../",script&&script.src||new URL("javascripts/study-session.js",document.baseURI));let active=null,graph=null,graphPromise=null;const copy=value=>JSON.parse(JSON.stringify(value));const el=(tag,attrs,text)=>{const n=document.createElement(tag);Object.entries(attrs||{}).forEach(([k,v])=>n.setAttribute(k,v));if(text!=null)n.textContent=text;return n;};const button=(text,action,attrs)=>el("button",{type:"button","data-ss-action":action,...attrs},text);const focus=node=>{if(node&&node.isConnected)node.focus({preventScroll:true});};function identity(){try{const ws=window.MkAccountWorkspaces;return{ws,owner:ws&&ws.activeOwner()||"",profile:ws&&ws.ownerFromProfile()||""};}
catch(_){return{ws:null,owner:"",profile:""};}}
const same=(a,b)=>a.ws===b.ws&&a.owner===b.owner&&a.profile===b.profile;const routeId=()=>new URL(window.location.href).searchParams.get("study-session")||"";function currentLoc(){return window.location.pathname.startsWith(siteRoot.pathname)?window.location.pathname.slice(siteRoot.pathname.length):"";}
function published(){const api=window.__findSearchV2,data=api&&api.getPublishedConceptsSnapshot&&api.getPublishedConceptsSnapshot();return data&&data.ok?{version:1,nodes:Object.fromEntries(data.items.map(item=>[item.loc,item]))}:graph;}
async function loadPublished(){if(published())return true;if(!graphPromise){const url=new URL("assets/concept-graph.json",siteRoot).href;graphPromise=(async()=>{const response=await fetch(url,{credentials:"same-origin"});if(!response.ok)throw new Error("index");const value=await response.json();if(!value||value.version!==1||!value.nodes||Array.isArray(value.nodes))throw new Error("index");graph=value;return true;})().catch(()=>false).finally(()=>{graphPromise=null;});}
return graphPromise;}
function capture(s){return{generation:s.generation,identity:s.identity,href:window.location.href};}
function valid(s,t){if(active!==s||!s.root.isConnected||t.generation!==s.generation||t.href!==window.location.href)return false;if(!same(t.identity,identity())){invalidate(s);refreshIdentity(s);return false;}
return!window.__mkAccountWorkspaceSwitching;}
function message(s,text,error){s.notice.textContent=text||"";s.notice.dataset.error=error?"true":"false";}
function invalidate(s){busy(s,false);s.generation++;s.readVersion++;s.identity=identity();s.session=null;s.selection=null;s.revision=null;s.busy=false;s.confirmEnd=false;render(s);message(s,"Account data changed. Reload this workspace to continue.",true);}
function refreshIdentity(s){if(s.identity.owner&&!window.__mkAccountWorkspaceSwitching&&!s.root.hidden)read(s);}
function settings(s){return{expectedOwner:s.identity.owner,expectedRevision:s.revision};}
function busy(s,value){s.busy=value;if(value)s.readVersion++;if(value&&s.root.contains(document.activeElement))focus(s.notice);s.root.setAttribute("aria-busy",String(value));s.root.querySelectorAll("button,input,select").forEach(n=>{if(value){n.dataset.ssDisabled=String(n.disabled);n.disabled=true;}
else if(n.dataset.ssDisabled!=null){n.disabled=n.dataset.ssDisabled==="true";delete n.dataset.ssDisabled;}});}
function finish(s,t){const current=valid(s,t);if(active===s&&s.root.isConnected&&t.generation===s.generation){busy(s,false);if(!current)message(s,"Account data is updating. Reload shortly.",true);}
return current;}
const pending=session=>session&&session.items.find(item=>item.state==="pending");function available(item){if(!item)return false;const data=published(),meta=data&&data.nodes[item.loc];return!!meta&&meta.curriculumStatus!=="retired"&&window.MkStudySetsCore.isConceptLocation(item.loc);}
function targetUrl(session,item){if(!item||!available(item))return"";const url=new URL(item.loc,siteRoot);url.searchParams.set("study-session",session.id);return url.href;}
function navigate(s,t){if(!valid(s,t)||!s.session)return;const item=pending(s.session),href=item&&targetUrl(s.session,item);if(!item){render(s);focus(s.heading);return;}
if(!href){render(s);message(s,published()?"This concept is no longer available. Skip it to continue.":"Your progress is saved. The concept list could not load. Use Reload progress to try again.",true);return;}
if(currentLoc()===item.loc&&routeId()===s.session.id){render(s);focus(s.heading);return;}
message(s,"Opening the next concept…");busy(s,true);window.location.assign(href);}
function appendActions(s,...nodes){const row=el("div",{class:"ss-actions"});row.append(...nodes);s.content.append(row);return row;}
function render(s){s.content.replaceChildren();s.confirmEnd=false;const session=s.session,item=pending(session);s.heading.textContent=session?session.name:"A focused review";if(!s.finder&&(!session||session.id!==routeId())){s.heading.textContent="Review session";s.content.append(el("p",{},s.revision==null?"Load this workspace to continue.":"This session is no longer current in this workspace."));appendActions(s,button("Reload","reload"),el("a",{href:new URL("find.html#study-sets",siteRoot).href},"Open study sets"));return;}
if(session){const done=session.items.filter(x=>x.state==="done").length,skipped=session.items.filter(x=>x.state==="skipped").length;const remaining=session.items.length-done-skipped,terminal=["completed","ended"].includes(session.status);const meter=el("progress",{max:session.items.length,value:done+skipped,"aria-label":"Session progress"});const stats=el("div",{class:"ss-stats"});stats.append(el("strong",{},done+" done"),el("span",{},skipped+" skipped"),el("span",{},remaining+" remaining"));s.content.append(meter,stats);if(terminal){s.content.append(el("p",{class:"ss-outcome"},session.status==="completed"?"Session complete":"Session ended"));const list=el("ol",{class:"ss-summary"});session.items.forEach(x=>{const row=el("li");row.append(el("span",{},x.title),el("small",{},x.state==="done"?"Done":x.state==="skipped"?"Skipped":"Not reviewed"));list.append(row);});s.content.append(list,el("p",{class:"ss-muted"},"Progress records this session’s actions; mastery ratings stay separate."));appendActions(s,button("Download summary","summary"));}else{const here=!s.finder&&item&&currentLoc()===item.loc;s.content.append(el("p",{class:"ss-current"},(session.status==="paused"?"Paused · ":"Next · ")+item.title));if(session.status==="paused")appendActions(s,button("Resume review","resume",{class:"ss-primary"}),button("End session","end"));else if(here){appendActions(s,button("Done & next","done",{class:"ss-primary"}),button("Skip & next","skipped"),button("Pause","pause"),button("Self-test","selftest"),button("AI check","ai"));const more=el("details",{class:"ss-more"});more.append(el("summary",{},"Session options"),button("End session","end"));s.content.append(more);targetSelfTestLabel(s,!!(window.MkConceptFold&&window.MkConceptFold.isSelfTestEnabled()));}else{if(!published()){s.content.append(el("p",{class:"ss-muted"},"The concept list could not load. Reload before continuing."));appendActions(s,button("Reload concept list","reload",{class:"ss-primary"}),button("Pause","pause"),button("End session","end"));}else appendActions(s,button(available(item)?"Continue review →":"Skip unavailable concept","continue",{class:"ss-primary"}),button("Pause","pause"),button("End session","end"));if(!s.finder&&session.items.some(x=>x.loc===currentLoc()&&x.state!=="pending"))s.content.append(el("p",{class:"ss-muted"},"This concept is already recorded. Continue with the next one."));}}
if(!terminal)return;}
if(s.finder&&s.selection){const nodes=published()?.nodes||{};const choices=s.selection.items.filter(x=>available(x)&&(s.selection.source.includeEnrichment||(x.curriculumStatus!=="enrichment"&&nodes[x.loc].curriculumStatus!=="enrichment"))),section=el("div",{class:"ss-plan"});section.append(el("h3",{},"Review “"+s.selection.name+"”"),el("p",{class:"ss-muted"},choices.length+" available · follows your set order"));const controls=el("div",{class:"ss-choices"});(choices.length>5?[5,10]:[5]).forEach(n=>{const b=button("","start",{"data-ss-count":n,class:"ss-choice"});b.disabled=!choices.length;const actual=Math.min(n,choices.length);b.append(el("strong",{},actual+" concept"+(actual===1?"":"s")),el("span",{},choices.length<n?"Up to "+n+" · all available":"First "+n+" in this set"));controls.append(b);});section.append(controls);s.content.append(section);if(!choices.length)message(s,published()?"This set has no currently available concepts.":"The concept list is loading. Reload shortly.",true);}else if(s.finder&&!session)s.content.append(el("p",{},"Open a saved study set, then choose Review this set."));}
async function read(s){const token=capture(s),version=++s.readVersion;const result=await s.repo.read(s.identity.owner?{expectedOwner:s.identity.owner}:undefined);if(!valid(s,token)||version!==s.readVersion)return;if(!result.ok){s.revision=null;s.session=null;render(s);message(s,result.message,true);s.recovery.hidden=!["storage_corrupt","schema_unsupported"].includes(result.code);return;}
s.identity=identity();s.revision=result.value.revision;s.session=result.value.session;s.recovery.hidden=true;render(s);message(s,"");}
async function mutate(s,action,count){if(s.revision==null){message(s,"Reload before changing your session.",true);return;}
const token=capture(s),session=s.session,item=pending(session),options=settings(s);message(s,"Saving progress…");busy(s,true);let result;if(action==="start"){if(!s.selection){busy(s,false);return;}
if(!s.request||s.request.count!==count)s.request={count,id:window.crypto.randomUUID()};result=await s.repo.start(copy(s.selection),count,{...options,requestId:s.request.id});}else if(["done","skipped"].includes(action)){if(!session||!item){busy(s,false);return;}
result=await s.repo.step(session.id,item.loc,action,options);}else{if(!session){busy(s,false);return;}
result=await s.repo[action](session.id,options);}
if(!finish(s,token))return;if(!result.ok){message(s,result.message,true);return;}
s.revision=result.value.revision;s.session=result.value.session;render(s);message(s,"");if(["start","resume","done","skipped"].includes(action)&&s.session.status==="active")navigate(s,token);else{focus(s.heading);if(action==="pause")message(s,"Paused. Your place is saved on this browser.");}}
async function useTool(s,kind){const token=capture(s),session=s.session,item=pending(session);if(!session||session.status!=="active"||s.finder||!item||item.loc!==currentLoc()||session.id!==routeId())return;if(kind==="selftest"){const api=window.MkConceptFold;if(!api||!api.setSelfTest){message(s,"Self-test is still loading. You can continue reading.");return;}
const enable=!(api.isSelfTestEnabled&&api.isSelfTestEnabled()),result=api.setSelfTest(enable);targetSelfTestLabel(s,!!(result&&result.enabled));message(s,result&&result.ok?enable?"Recall the ideas, then open each section to check.":"Self-test stopped.":"No sections are available to fold on this page.");return;}
if(s.toolBusy)return;if(window.__mkStartupFeatureEnabled&&!window.__mkStartupFeatureEnabled("aiQuiz")){message(s,"AI checks are turned off. Continue reading or use Self-test.");return;}
s.toolBusy=true;try{if(!window.AIMCQQuiz&&window.MkStartupPrefs&&window.MkStartupPrefs.ensureFeature)await window.MkStartupPrefs.ensureFeature("aiQuiz");if(!valid(s,token)||s.session!==session)return;const api=window.AIMCQQuiz;if(!api||!api.open){message(s,"AI checks are still loading. Continue reading or try again.");return;}
if(api.availabilityKnown&&api.availabilityKnown()&&api.isAvailable&&!api.isAvailable()){message(s,"No AI check is available now. Continue reading or use Self-test.");return;}
const opened=await api.open();if(valid(s,token)&&s.session===session&&!opened)message(s,"The AI check did not open. You can continue reading or use Self-test.");}finally{s.toolBusy=false;}}
function targetSelfTestLabel(s,on){const control=s.content.querySelector('[data-ss-action="selftest"]');if(control){control.textContent=on?"Stop self-test":"Self-test";control.setAttribute("aria-pressed",String(on));}}
async function download(s,recovery){const token=capture(s),result=recovery?await s.repo.exportRecovery({expectedOwner:s.identity.owner}):await s.repo.exportSummary(s.session.id,{expectedOwner:s.identity.owner});if(!valid(s,token))return;if(!result.ok){message(s,result.message,true);return;}
const url=URL.createObjectURL(new Blob([result.value.text],{type:recovery?"application/json":"text/markdown;charset=utf-8"}));const link=el("a",{href:url,download:recovery?"study-session-recovery.json":"study-session.md"});document.body.append(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);message(s,"Download prepared.");}
function hide(s){if(!s.finder)return;if(s.root.hidden&&!s.shell.hasAttribute("data-study-session-open"))return;busy(s,false);s.generation++;s.root.hidden=true;s.shell.removeAttribute("data-study-session-open");}
async function close(s){if(!s.finder)return;hide(s);const token=capture(s),opener=s.returnFocus,action=opener&&opener.getAttribute("data-wss-action");const opening=window.MkStudySets&&window.MkStudySets.open(),interim=document.activeElement;await opening;if(!valid(s,token)||!s.root.hidden)return;if(document.activeElement!==interim&&document.activeElement!==document.body&&document.activeElement!==opener)return;const replacement=["review","session"].includes(action)?s.shell.querySelector('[data-wss-action="'+action+'"]'):null;focus(opener&&opener.isConnected?opener:replacement);}
async function act(s,target){if(s.busy)return;if(!same(s.identity,identity())){invalidate(s);return;}
const action=target.dataset.ssAction;if(action==="back")return close(s);if(action==="reload"){await loadPublished();return read(s);}
if(["selftest","ai"].includes(action))return useTool(s,action);if(action==="summary"||action==="recovery")return download(s,action==="recovery");if(action==="end"){const group=el("div",{class:"ss-confirm",role:"group","aria-label":"End this session?"});group.append(el("span",{},"End this session with the remaining concepts unreviewed?"),button("End session now","confirm-end"),button("Keep reviewing","cancel-end"));target.replaceWith(group);focus(group.querySelector("button"));return;}
if(action==="cancel-end"){render(s);focus(s.content.querySelector(".ss-more summary")||s.content.querySelector('[data-ss-action="end"]'));return;}
if(action==="continue"){if(!published()){render(s);message(s,"The concept list is unavailable. Reload before continuing.",true);return;}
const token=capture(s);if(available(pending(s.session)))return navigate(s,token);return mutate(s,"skipped");}
if(["done","skipped"].includes(action)&&(s.finder||!s.session||s.session.id!==routeId()||pending(s.session)?.loc!==currentLoc()))return;return mutate(s,action==="confirm-end"?"end":action,Number(target.dataset.ssCount));}
function init(){const shell=document.querySelector(".wiki-finder"),article=document.querySelector("article.md-content__inner");if(!window.MkStudySessionCore||!window.MkStudySetsCore||(!shell&&(!article||!ID.test(routeId()))))return null;if(active&&active.root.isConnected&&active.page===window.location.pathname)return active;if(active)active.generation++;const root=el("section",{class:"study-session",id:"study-session","aria-label":"Review session"});const s={root,shell,finder:!!shell,page:window.location.pathname,identity:identity(),generation:1,readVersion:0,revision:null,session:null,selection:null,busy:false};active=s;s.repo=window.MkStudySessionCore.createRepository({getPublished:published,baseUrl:siteRoot.href});const header=el("header",{class:"ss-header"}),title=el("div");s.heading=el("h2",{tabindex:"-1"},"Review session");title.append(el("small",{},"FOCUSED REVIEW"),s.heading);header.append(title);header.append(shell?button("← Study sets","back"):el("a",{href:new URL("find.html#study-sets",siteRoot).href},"Study sets ↗"));root.append(header);s.notice=el("p",{class:"ss-notice",role:"status","aria-live":"polite",tabindex:"-1"});s.content=el("div",{class:"ss-content"});root.append(s.notice,s.content);const footer=el("div",{class:"ss-footer"});s.recovery=button("Download original data","recovery");s.recovery.hidden=true;footer.append(el("small",{},"Saved on this browser"),button("Reload progress","reload"),s.recovery);root.append(footer);root.addEventListener("click",e=>{const target=e.target.closest("[data-ss-action]");if(target){const token=capture(s);act(s,target).catch(()=>{if(finish(s,token))message(s,"This action could not finish. Reload or try again.",true);});}});if(shell){shell.append(root);root.hidden=true;}
else{const h1=article.querySelector("h1");if(h1)h1.after(root);else article.prepend(root);render(s);loadPublished().then(()=>read(s));}
return s;}
async function show(selection){const s=init();if(!s||!s.finder||s.busy)return;if(!same(s.identity,identity()))invalidate(s);if(s.root.hidden)s.returnFocus=document.activeElement;if(window.MkStudySets&&window.MkStudySets.hide)window.MkStudySets.hide();s.generation++;s.selection=selection?copy(selection):null;s.request=null;s.shell.setAttribute("data-study-session-open","");s.root.hidden=false;render(s);focus(s.heading);s.root.scrollIntoView({block:"start",behavior:"auto"});await read(s);}
function changed(event){const s=active;if(!s||!s.root.isConnected)return;if(event.type==="pageshow")busy(s,false);if(!same(s.identity,identity())){invalidate(s);refreshIdentity(s);return;}
if(s.busy)return;if(event.type!=="storage"||event.key==null||event.key===KEY)read(s);}
["mk-account-workspaces-ready","mk-account-workspace-changed","mk-study-session-changed","storage","pageshow"].forEach(name=>window.addEventListener(name,changed));window.addEventListener("pagehide",()=>{if(active)active.generation++;});document.addEventListener("DOMContentSwitch",init);window.MkStudySession=Object.freeze({version:1,open:set=>show(set),show:()=>show(null),hide:()=>{if(active&&active.root.isConnected)hide(active);}});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();})();