(function(){"use strict";if(window.MkStudySets||window.__mkExamMode)return;let active=null;const KEY="mk_account_study_sets_v1";const clone=value=>JSON.parse(JSON.stringify(value));const uid=()=>window.crypto.randomUUID();const counted=(count,noun)=>count+" "+noun+(count===1?"":"s");function identity(){try{const ws=window.MkAccountWorkspaces;return{ws,owner:ws&&ws.activeOwner()||"",profile:ws&&ws.ownerFromProfile()||""};}
catch(_){return{ws:null,owner:"",profile:""};}}
const sameIdentity=(a,b)=>a.ws===b.ws&&a.owner===b.owner&&a.profile===b.profile;let leaveGuardBound=false;function protectDraft(event){const s=active;if(!s||!s.dirty||!s.root.isConnected||!sameIdentity(s.identity,identity()))return;event.preventDefault();event.returnValue="";}
function setDirty(s,value){s.dirty=!!value;const needed=active===s&&s.dirty;if(needed===leaveGuardBound)return;leaveGuardBound=needed;window[needed?"addEventListener":"removeEventListener"]("beforeunload",protectDraft);}
function el(tag,attrs,text){const node=document.createElement(tag);Object.entries(attrs||{}).forEach(([key,value])=>node.setAttribute(key,value));if(text!=null)node.textContent=text;return node;}
function button(text,action,attrs){return el("button",Object.assign({type:"button","data-wss-action":action},attrs),text);}
function published(){const api=window.__findSearchV2,result=api&&api.getPublishedConceptsSnapshot&&api.getPublishedConceptsSnapshot();return result&&result.ok?{version:1,nodes:Object.fromEntries(result.items.map(item=>[item.loc,item]))}:null;}
const baseUrl=()=>new URL("./",window.location.href).href;function status(s,text,error){if(!s.root.isConnected)return;s.statusVersion++;s.pendingReloadNotice=false;s.status.textContent=text||"";s.status.dataset.error=error?"true":"false";}
const capture=s=>({generation:s.generation,identity:s.identity});function valid(s,token){if(active!==s||!s.root.isConnected||token.generation!==s.generation)return false;if(!sameIdentity(token.identity,identity())){resetIdentity(s);return false;}
return!window.__mkAccountWorkspaceSwitching;}
const options=s=>({expectedOwner:s.identity.owner,expectedRevision:s.revision});function focus(node){if(node&&node.isConnected)node.focus({preventScroll:true});}
function unloadedVisibleLibrary(s){return!s.root.hidden&&s.shell.hasAttribute("data-study-sets-open")&&s.revision==null&&!s.draft&&!s.preview&&!s.dirty&&!s.busy;}
function readInitialIdentity(s){const token=capture(s),request=s.readVersion;const current=()=>active===s&&s.root.isConnected&&token.generation===s.generation&&sameIdentity(token.identity,identity())&&request===s.readVersion&&unloadedVisibleLibrary(s);status(s,"Loading your study sets…");s.pendingReloadNotice=true;Promise.resolve(token.identity.ws.ready).catch(()=>{}).then(()=>{if(current()&&!window.__mkAccountWorkspaceSwitching)return readLibrary(s,false);}).catch(()=>{if(current())status(s,"Could not read your study sets. Retry.",true);});}
function resetIdentity(s){const hadOwner=!!s.identity.owner;const hydrate=!hadOwner&&unloadedVisibleLibrary(s);setBusy(s,false);s.generation++;s.identity=identity();s.sets=[];s.revision=null;s.readVersion++;s.draft=null;s.preview=null;s.busy=false;setDirty(s,false);renderLibrary(s);renderEditor(s);status(s,hadOwner?"Account changed. Reload your study sets for this workspace.":"Local storage is ready. Reload your study sets.",hadOwner);s.pendingReloadNotice=true;if(hydrate&&s.identity.owner&&s.identity.ws&&s.identity.ws.ready)readInitialIdentity(s);}
function setBusy(s,value){s.busy=value;if(value)s.readVersion++;if(value&&s.root.contains(document.activeElement))focus(s.status);s.root.querySelectorAll("button,input,textarea").forEach(node=>{if(value){node.dataset.wssDisabled=node.disabled?"true":"false";node.disabled=true;}
else if(node.dataset.wssDisabled!=null){node.disabled=node.dataset.wssDisabled==="true";delete node.dataset.wssDisabled;}});s.root.setAttribute("aria-busy",String(value));}
function finishOperation(s,token){const current=valid(s,token);if(active===s&&s.root.isConnected&&token.generation===s.generation){setBusy(s,false);if(!current)status(s,"Account data is updating. Retry shortly.",true);}
return current;}
async function readLibrary(s,announce){const token=capture(s),request=++s.readVersion,messageVersion=s.statusVersion;const result=await s.repo.read(s.identity.owner?{expectedOwner:s.identity.owner}:undefined);if(!valid(s,token)||request!==s.readVersion)return false;if(!result.ok){s.revision=null;s.sets=[];renderLibrary(s);s.recovery.hidden=!["storage_corrupt","schema_unsupported"].includes(result.code);status(s,result.message+(s.draft?" Your draft is still here.":""),true);return false;}
s.sets=result.value.sets;s.revision=result.value.revision;if(s.draft&&!s.draft.isNew){const latest=s.sets.find(set=>set.id===s.draft.set.id);if(s.dirty){s.draft.conflict=!latest||JSON.stringify(latest)!==JSON.stringify(s.draft.original);}else{s.draft=latest?{set:clone(latest),original:clone(latest),isNew:false}:null;renderEditor(s);}}
s.recovery.hidden=true;renderLibrary(s);if(s.draft&&s.draft.conflict){status(s,"This set changed elsewhere. Download your draft, or discard changes to load the saved version.",true);return true;}
if(announce||((s.status.dataset.error==="true"||s.pendingReloadNotice)&&messageVersion===s.statusVersion))status(s,s.draft?"Library reloaded. Your draft is unchanged.":"Library ready.");return true;}
function visible(s,value){s.root.hidden=!value;if(value)s.shell.setAttribute("data-study-sets-open","");else s.shell.removeAttribute("data-study-sets-open");s.shell.querySelectorAll('[data-study-sets-library],[data-study-set-create]').forEach(node=>node.setAttribute('aria-expanded',String(value)));}
function suspend(s){if(s.shell.hasAttribute("data-study-sets-open"))s.suspended=true;visible(s,false);}
function open(s,trigger){if(!sameIdentity(s.identity,identity()))resetIdentity(s);if(window.MkStudySession&&window.MkStudySession.hide)window.MkStudySession.hide();if(!s.shell.hasAttribute("data-study-sets-open")&&!s.suspended){s.returnFocus=trigger;s.returnScroll=window.scrollY;}
s.suspended=false;visible(s,true);focus(s.heading);s.root.scrollIntoView({block:"start",behavior:"auto"});}
function back(s){s.suspended=false;visible(s,false);focus(s.returnFocus&&s.returnFocus.isConnected?s.returnFocus:s.entry.querySelector("button"));window.scrollTo({top:s.returnScroll||0,behavior:"auto"});}
async function createDraft(s,trigger){if(s.busy)return;open(s,trigger);if(s.dirty){status(s,"Save or discard your changes before using another selection.",true);return;}
const api=window.__findSearchV2,snapshot=api&&api.getSelectionSnapshot&&api.getSelectionSnapshot();if(!snapshot||!snapshot.ok){const messages={empty_selection:"Select at least one current concept in Finder.",index_failed:"Finder could not load its index. Return to Finder and retry.",not_ready:"Finder is still loading. Try again shortly."};status(s,messages[snapshot&&snapshot.code]||"Return to Finder and run your search again.",true);return;}
s.generation++;const token=capture(s),requestId=uid();const result=await s.repo.prepareDraft(snapshot,"New study set",{requestId});if(!valid(s,token))return;if(!result.ok){status(s,result.message,true);return;}
s.preview=null;s.draft={set:result.value.set,snapshot,requestId,isNew:true,original:null};setDirty(s,true);s.visibleItems=30;renderEditor(s);status(s,counted(snapshot.items.length,"selected concept")+" captured."+(snapshot.excludedCount?" "+snapshot.excludedCount+" outside the learning scope omitted.":""));focus(s.root.querySelector("[name=wss-name]"));await readLibrary(s,false);}
function renderLibrary(s){s.library.replaceChildren();s.library.append(el("p",{class:"wss-library-count"},s.revision==null?"Study sets not loaded":counted(s.sets.length,"saved set")));if(!s.sets.length)s.library.append(el("p",{class:"wss-muted"},s.revision==null?"Reload to open your library.":"Save a Finder selection to start your first set."));s.sets.forEach(set=>{const item=button("","select",{"data-wss-id":set.id,"aria-pressed":String(!!s.draft&&s.draft.set.id===set.id)});item.append(el("strong",{},set.name),el("span",{},counted(set.items.length,"concept")));s.library.append(item);});}
function formValue(s){if(!s.draft)return;const name=s.root.querySelector("[name=wss-name]"),note=s.root.querySelector("[name=wss-note]");if(name)s.draft.set.name=name.value;if(note)s.draft.set.note=note.value;}
function renderEditor(s){s.editor.replaceChildren();s.root.dataset.detail=s.draft||s.preview?"true":"false";if(s.preview){renderImport(s);return;}
if(!s.draft){s.editor.append(el("h3",{},"Keep a study plan together"),el("p",{class:"wss-muted"},"Save a revision range or arrange concepts for a tutorial. Each set keeps its own order and notes."),button("Use Finder selection","create"));return;}
const draft=s.draft,fields=el("div",{class:"wss-fields"});const nameLabel=el("label",{},"Set name"),name=el("input",{name:"wss-name",maxlength:"100",required:"",autocomplete:"off"});name.value=draft.set.name;nameLabel.append(name);const noteLabel=el("label",{},"Notes"),note=el("textarea",{name:"wss-note",maxlength:"1000",rows:"2",placeholder:"What are you preparing?"});note.value=draft.set.note;noteLabel.append(note);fields.append(nameLabel,noteLabel);s.editor.append(fields);s.editor.append(el("p",{class:"wss-source"},"From Finder"+(draft.set.source.expression?" · "+draft.set.source.expression:"")+" · "+counted(draft.set.items.length,"concept")));const actions=el("div",{class:"wss-actions"});actions.append(button(draft.isNew?"Save set":"Save changes","save",{class:"wss-primary"}),button("Download Markdown","markdown"),button("Download JSON","draft-json"),button("Discard changes","discard"));if(!draft.isNew)actions.append(button("Delete set","delete"));s.editor.append(actions);if(!draft.isNew&&window.MkStudySession)s.editor.append(button("Review this set →","review",{class:"wss-primary wss-review"}));const order=el("div",{class:"wss-order-heading"});order.append(el("h3",{},"Concept order"),el("span",{class:"wss-muted"},"Move or remove items"));s.editor.append(order);const list=el("ol",{class:"wss-items","aria-label":"Concept order"});s.editor.append(list);const graph=published();draft.set.items.slice(0,s.visibleItems).forEach((item,index)=>{const row=el("li",{"data-wss-loc":item.loc}),meta=graph&&graph.nodes[item.loc],info=el("div",{class:"wss-item-info"});const available=meta&&meta.curriculumStatus!=="retired"&&window.MkStudySetsCore.isConceptLocation(item.loc);const title=available&&typeof meta.title==="string"?meta.title.trim():item.title;if(available)info.append(el("a",{href:new URL(item.loc,baseUrl()).href},title));else info.append(el("span",{},item.title),el("small",{},graph?"Unavailable":"Reload when Finder is ready to check links"));const controls=el("div",{class:"wss-item-actions"});const up=button("↑","up",{"data-wss-index":index,"aria-label":"Move up: "+title});up.disabled=index===0;const down=button("↓","down",{"data-wss-index":index,"aria-label":"Move down: "+title});down.disabled=index===draft.set.items.length-1;const remove=button("×","remove",{"data-wss-index":index,"aria-label":"Remove: "+title});remove.disabled=draft.set.items.length===1;controls.append(up,down,remove);row.append(info,controls);list.append(row);});if(draft.set.items.length>s.visibleItems)s.editor.append(button("Show more ("+(draft.set.items.length-s.visibleItems)+" remaining)","more"));renderLibrary(s);}
function renderImport(s){s.editor.append(el("h3",{},"Import preview"),el("p",{},counted(s.preview.sets.length,"set")+(s.preview.sets.length===1?" will be added as a new copy.":" will be added as new copies.")));const list=el("ul",{class:"wss-import-list"});s.preview.sets.forEach(set=>list.append(el("li",{},set.name+" · "+counted(set.items.length,"concept"))));s.editor.append(list);s.preview.warnings.forEach(warning=>s.editor.append(el("p",{class:"wss-muted"},warning)));const actions=el("div",{class:"wss-actions"});actions.append(button("Import as new sets","import",{class:"wss-primary"}),button("Cancel import","cancel-import"));s.editor.append(actions);}
async function save(s){formValue(s);if(!s.draft)return;if(!s.draft.set.name.trim()){status(s,"Give this set a name.",true);focus(s.root.querySelector("[name=wss-name]"));return;}
if(s.revision==null){status(s,"Reload the library before saving. Your draft is still here.",true);return;}
if(s.draft.conflict){status(s,"This set changed elsewhere. Download your draft, or discard changes to load the saved version.",true);return;}
const token=capture(s),draft=s.draft,settings=options(s);setBusy(s,true);status(s,"Saving…");const result=draft.isNew?await s.repo.create({...draft.snapshot,items:draft.set.items},draft.set.name,{...settings,requestId:draft.requestId,note:draft.set.note}):await s.repo.update(draft.set.id,{name:draft.set.name,note:draft.set.note,orderedLocations:draft.set.items.map(item=>item.loc)},settings);if(!finishOperation(s,token))return;if(!result.ok){status(s,result.message+" Your draft is still here.",true);return;}
s.sets=result.value.sets;s.revision=result.value.revision;const stored=s.sets.find(set=>set.id===result.value.setId);s.draft={set:clone(stored),original:clone(stored),isNew:false};setDirty(s,false);renderEditor(s);status(s,"Saved on this browser.");}
function download(s,token,text,filename,type){if(!valid(s,token))return;const url=URL.createObjectURL(new Blob([text],{type})),link=el("a",{href:url,download:filename});document.body.append(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);status(s,"Download prepared.");}
async function exportFile(s,kind){formValue(s);const token=capture(s);let result;if(kind==="backup")result=await s.repo.exportBackup({expectedOwner:s.identity.owner});else if(kind==="recovery")result=await s.repo.exportRecovery({expectedOwner:s.identity.owner});else if(s.draft)result=await s.repo.exportDraft(clone(s.draft.set));if(!valid(s,token)||!result)return;if(!result.ok){status(s,result.message,true);return;}
const md=kind==="markdown",value=result.value;download(s,token,md?value.markdown:kind==="draft-json"?value.backup:value.text,"study-sets"+(kind==="recovery"?"-recovery":"")+(md?".md":".json"),md?"text/markdown;charset=utf-8":"application/json");}
async function previewFile(s,file){if(!file)return;if(s.busy)return;if(s.dirty){status(s,"Save or discard your changes before importing.",true);return;}
if(file.size>524288){status(s,"This backup is too large (maximum 512 KB).",true);return;}
s.generation++;const token=capture(s);setBusy(s,true);status(s,"Reading backup…");let result;try{result=await s.repo.previewImport(await file.text());}catch(_){result={ok:false,message:"The backup file could not be read."};}
if(!finishOperation(s,token))return;if(!result.ok){status(s,result.message,true);return;}
s.preview=result.value;s.importRequestId=uid();s.draft=null;renderEditor(s);status(s,"Review these copies before importing.");}
async function importSets(s){if(!s.preview)return;if(s.revision==null){status(s,"Reload the library before importing.",true);return;}
const token=capture(s);setBusy(s,true);status(s,"Importing…");const result=await s.repo.importAsNew(s.preview,{...options(s),requestId:s.importRequestId});if(!finishOperation(s,token))return;if(!result.ok){status(s,result.message,true);return;}
s.preview=null;s.sets=result.value.sets;s.revision=result.value.revision;renderLibrary(s);renderEditor(s);status(s,counted(result.value.setIds.length,"set")+" imported.");}
async function deleteSet(s){if(!s.draft||s.draft.isNew)return;const token=capture(s);setBusy(s,true);status(s,"Deleting…");const result=await s.repo.remove(s.draft.set.id,options(s));if(!finishOperation(s,token))return;if(!result.ok){status(s,result.message,true);return;}
s.draft=null;setDirty(s,false);s.sets=result.value.sets;s.revision=result.value.revision;renderLibrary(s);renderEditor(s);status(s,"Set deleted.");}
async function act(s,target){if(s.busy)return;if(!sameIdentity(s.identity,identity())){resetIdentity(s);return;}
const action=target.dataset.wssAction;if(action==="back")return back(s);if(action==="reload")return readLibrary(s,true);if(action==="session")return window.MkStudySession&&window.MkStudySession.show();if(action==="review"){if(s.dirty||s.draft?.isNew){status(s,"Save your changes before starting a review.",true);return;}
return window.MkStudySession&&s.draft&&window.MkStudySession.open(clone(s.draft.set));}
if(action==="create")return createDraft(s,target);if(action==="save")return save(s);if(["markdown","draft-json","backup","recovery"].includes(action))return exportFile(s,action);if(action==="import")return importSets(s);if(action==="cancel-import"){s.preview=null;renderEditor(s);status(s,"Import cancelled.");focus(s.heading);return;}
if(action==="select"){if(s.dirty){status(s,"Save or discard your changes before opening another set.",true);return;}
const set=s.sets.find(item=>item.id===target.dataset.wssId);if(!set)return;s.generation++;s.preview=null;s.draft={set:clone(set),original:clone(set),isNew:false};s.visibleItems=30;renderEditor(s);status(s,"");focus(s.root.querySelector("[name=wss-name]"));return;}
if(action==="discard"){s.generation++;const latest=s.draft&&!s.draft.isNew&&s.sets.find(set=>set.id===s.draft.set.id);s.draft=latest?{set:clone(latest),original:clone(latest),isNew:false}:null;setDirty(s,false);renderEditor(s);status(s,"Changes discarded.");focus(s.root.querySelector("[name=wss-name]")||s.heading);return;}
if(action==="delete"){const confirm=el("div",{class:"wss-confirm",role:"group","aria-label":"Delete this set?"});confirm.append(el("span",{},"Delete this set?"),button("Delete this set","confirm-delete"),button("Keep set","cancel-delete"));target.replaceWith(confirm);focus(confirm.querySelector("button"));return;}
if(action==="confirm-delete")return deleteSet(s);if(action==="cancel-delete"){formValue(s);renderEditor(s);focus(s.root.querySelector('[data-wss-action="delete"]'));return;}
if(action==="more"){formValue(s);const index=s.visibleItems;s.visibleItems+=30;renderEditor(s);const row=s.root.querySelectorAll(".wss-items li")[index];focus(row&&row.querySelector("a,button:not(:disabled)")||s.heading);return;}
if(["up","down","remove"].includes(action)&&s.draft){formValue(s);const items=s.draft.set.items,index=Number(target.dataset.wssIndex),next=index+(action==="up"?-1:1);if(action==="remove"){if(items.length<2)return;items.splice(index,1);}
else if(index>=0&&next>=0&&next<items.length)[items[index],items[next]]=[items[next],items[index]];else return;if(action!=="remove"&&next>=s.visibleItems)s.visibleItems+=30;setDirty(s,true);renderEditor(s);status(s,action==="remove"?"Concept removed from this draft.":"Order updated. Save to keep changes.");const row=s.root.querySelectorAll(".wss-items li")[Math.min(action==="remove"?index:next,items.length-1)];focus(row&&row.querySelector("button:not(:disabled)"));}}
function init(){const root=document.getElementById("study-sets-workspace");if(active&&active.root===root&&root&&root.isConnected)return;if(active){active.generation++;setDirty(active,false);}active=null;if(!root||window.__mkExamMode||!window.MkStudySetsCore)return;const shell=root.closest(".wiki-finder"),entry=shell.querySelector("[data-study-sets-entry]");const s={root,shell,entry,identity:identity(),generation:1,readVersion:0,statusVersion:0,revision:null,sets:[],draft:null,preview:null,visibleItems:30,dirty:false,busy:false};active=s;s.repo=window.MkStudySetsCore.createRepository({getPublished:published,baseUrl:baseUrl()});root.replaceChildren();const header=el("header",{class:"wss-header"}),title=el("div");s.heading=el("h2",{tabindex:"-1"},"Study sets");title.append(s.heading,el("p",{},"Saved on this browser"));header.append(title,button("← Back to Finder","back"));root.append(header);const tools=el("div",{class:"wss-tools"});tools.append(button("Reload","reload",{"aria-label":"Reload library"}),button("Backup JSON","backup",{"aria-label":"Export library JSON"}));if(window.MkStudySession)tools.append(button("Review session","session"));const fileLabel=el("label",{class:"wss-file"},"Import JSON"),input=el("input",{type:"file",accept:".json,application/json","aria-label":"Import study sets JSON"});fileLabel.append(input);tools.append(fileLabel);s.recovery=button("Download original data","recovery");s.recovery.hidden=true;tools.append(s.recovery);root.append(tools);s.status=el("p",{class:"wss-status",role:"status","aria-live":"polite",tabindex:"-1"});root.append(s.status);const layout=el("div",{class:"wss-layout"});s.library=el("nav",{class:"wss-library","aria-label":"Saved study sets"});s.editor=el("div",{class:"wss-editor"});layout.append(s.library,s.editor);root.append(layout);const failed=token=>{if(finishOperation(s,token))status(s,"This action could not finish. Your draft is still here; try again.",true);};root.addEventListener("click",event=>{const target=event.target.closest("[data-wss-action]");if(target){const pending=act(s,target),token=capture(s);pending.catch(()=>failed(token));}});root.addEventListener("input",event=>{if(event.target.matches("[name=wss-name],[name=wss-note]")){formValue(s);setDirty(s,true);}});input.addEventListener("change",()=>{const file=input.files&&input.files[0];input.value="";const pending=previewFile(s,file),token=capture(s);pending.catch(()=>failed(token));});entry.hidden=false;renderLibrary(s);renderEditor(s);if(window.location.hash==="#study-sets"){open(s,entry.querySelector("button"));readLibrary(s,false);}}
document.addEventListener("click",event=>{const trigger=event.target.closest("[data-study-set-create],[data-study-sets-library]"),s=active;if(!trigger||!s||s.busy||!s.shell.contains(trigger))return;if(trigger.hasAttribute("data-study-set-create"))createDraft(s,trigger).catch(()=>status(s,"Could not capture this selection. Return to Finder and retry.",true));else{open(s,trigger);readLibrary(s,false);}});function changed(event){const s=active;if(!s||!s.root.isConnected)return;if(!sameIdentity(s.identity,identity())){resetIdentity(s);return;}
if((event.type==="storage"&&(event.key===KEY||event.key==null))||event.type==="mk-study-sets-changed"){if(!s.busy&&s.shell.hasAttribute("data-study-sets-open"))status(s,"Library changed. Reload before saving; your draft will stay here.");}}
["mk-account-workspaces-ready","mk-account-workspace-changed","mk-study-sets-changed","storage","pageshow"].forEach(name=>window.addEventListener(name,changed));document.addEventListener("DOMContentSwitch",init);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();window.MkStudySets=Object.freeze({version:1,open:()=>{if(active&&active.root.isConnected&&!active.busy){open(active,active.entry.querySelector("button"));return readLibrary(active,false);}return Promise.resolve(false);},hide:()=>{if(active&&active.root.isConnected)suspend(active);}});window.addEventListener("hashchange",()=>{if(window.location.hash==="#study-sets")window.MkStudySets.open();});})();